'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import {Provider} from "react-redux";
import "./globals.css";
import { store} from "@/app/redux/store";
import React from "react";
import Navbar from "@/app/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const queryClient = new QueryClient()
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-gray-100"
      >
      <Provider store={store}>
          <QueryClientProvider client={queryClient}>
              <Navbar />
              <main className={"p-8"}>{children}</main>
          </QueryClientProvider>
      </Provider>
      </body>
    </html>
  );
}
